version: '3'
services:
  dev:
    image: node:10-jessie-slim
    volumes:
      - nodemodules:/usr/src/app/node_modules
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - 1234:1234
      - 1235:1235
    environment:
      - CHOKIDAR_USEPOLLING=1
volumes:
  nodemodules:
    external: true